@echo off
setlocal
cd /d "%~dp0"

set PYTHONPATH=src
set FACTORIO_AI_SLURM_ENABLED=1
set FACTORIO_AI_SLURM_MODE=scheduler
set FACTORIO_AI_SLURM_SCHEDULER_URL=http://100.112.168.31:8000
set FACTORIO_AI_SLURM_SCHEDULER_ACCOUNT=r1jae262
set FACTORIO_AI_SLURM_REMOTE_DIR=~/factorio-ai-worker
set FACTORIO_AI_SLURM_TASK_TIMEOUT_SECONDS=900
set FACTORIO_AI_SLURM_SCHEDULER_CPUS=3
set FACTORIO_AI_SLURM_SCHEDULER_GPUS=1
set FACTORIO_AI_SLURM_SCHEDULER_GPU_MODEL=a6000ada,a6000
set FACTORIO_AI_SLURM_SCHEDULER_PRIORITY=100
set FACTORIO_AI_SLURM_LAYOUT_GPU_MODELS=a6000ada,a6000
set FACTORIO_AI_SLURM_LAYOUT_CPUS=3
set FACTORIO_AI_SLURM_LAYOUT_PRIORITY=80
set FACTORIO_AI_VLLM_MODEL=Qwen/Qwen3.5-9B
set FACTORIO_AI_VLLM_ARGS=--max-model-len 32768 --gpu-memory-utilization 0.90 --enforce-eager
set FACTORIO_AI_VLLM_USE_FLASHINFER_SAMPLER=0
set FACTORIO_AI_VLLM_PORT=8000
set FACTORIO_AI_VLLM_STARTUP_SECONDS=420
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_ENABLED=1
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_DURATION_SECONDS=43200
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_HEARTBEAT_SECONDS=30
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_STALE_SECONDS=120
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_QUEUE_STALE_SECONDS=180
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_CPUS=1
set FACTORIO_AI_SCHEDULER_VLLM_CLIENT_CPUS=1
set FACTORIO_AI_SCHEDULER_VLLM_CLIENT_GPUS=1
set FACTORIO_AI_SCHEDULER_VLLM_SERVICE_PRIORITY=120
set FACTORIO_AI_LLM_GUIDED_JSON=1
set FACTORIO_AI_LLM_TIMEOUT=600
set FACTORIO_AI_REMOTE_STRATEGY_TIMEOUT_SECONDS=900
set FACTORIO_AI_BACKGROUND_LAYOUT_ENABLED=1
set FACTORIO_AI_BACKGROUND_LAYOUT_MODE=scheduler
set FACTORIO_AI_BACKGROUND_LAYOUT_MAX_ACTIVE_TASKS=1
set FACTORIO_AI_BACKGROUND_LAYOUT_INTERVAL_SECONDS=20

echo [factorio-ai] Running no-custom-mod Codex wait layout loop.
echo [factorio-ai] This submits simulation-only layout improvement work until runtime\codex-wait.json clears.
python -m factorio_ai.cli slurm-ensure-vllm-service --duration-seconds %FACTORIO_AI_SCHEDULER_VLLM_SERVICE_DURATION_SECONDS% || exit /b 1
python -m factorio_ai.cli run-no-mod-codex-wait-layout-loop --objective launch_rocket_program --cycles 0 --sleep-seconds 20
